$(".one").click(function(){
    $(".container").addClass("containerone");
  });
  $(".two").click(function(){
    $(".container").addClass("containertwo");
  });
  $(".three").click(function(){
    $(".container").addClass("containerthree");
  });
  $(".four").click(function(){
    $(".container").addClass("containerfour");
  });
  $(".five").click(function(){
    $(".container").addClass("containerfive");
  });
  $(".six").click(function(){
    $(".container").addClass("containersix");
  });
  $(".seven").click(function(){
    $(".container").addClass("containerseven");
  });
  $(".eight").click(function(){
    $(".container").addClass("containereight");
  });
  $(".nine").click(function(){
    $(".container").addClass("containernine");
  });
  $(".ten").click(function(){
    $(".container").addClass("containerten");
  });
  $(".eleve").click(function(){
    $(".container").addClass("containereleven");
  });
  $(".twelve").click(function(){
    $(".container").addClass("containertwelve");
  });
  $(".thirteen").click(function(){
    $(".container").addClass("containerthirteen");
  });
  $(".fourteen").click(function(){
    $(".container").addClass("containerfourteen");
  });
  $(".fifteen").click(function(){
    $(".container").addClass("containerfifteen");
  });
  $(".sixteen").click(function(){
    $(".container").addClass("containersixteen");
  });

  $(".one").click(function(){
    $(".container").addClass("containerone");
  });
  $(".two").click(function(){
    $(".container").addClass("containertwo");
  });
  $(".three").click(function(){
    $(".container").addClass("containerthree");
  });
  $(".four").click(function(){
    $(".container").addClass("containerfour");
  });
  $(".five").click(function(){
    $(".container").addClass("containerfive");
  });
  $(".six").click(function(){
    $(".container").addClass("containersix");
  });
  $(".seven").click(function(){
    $(".container").addClass("containerseven");
  });
  $(".eight").click(function(){
    $(".container").addClass("containereight");
  });
  $(".nine").click(function(){
    $(".container").addClass("containernine");
  });
  $(".ten").click(function(){
    $(".container").addClass("containerten");
  });
  $(".eleve").click(function(){
    $(".container").addClass("containereleven");
  });
  $(".twelve").click(function(){
    $(".container").addClass("containertwelve");
  });
  $(".thirteen").click(function(){
    $(".container").addClass("containerthirteen");
  });
  $(".fourteen").click(function(){
    $(".container").addClass("containerfourteen");
  });
  $(".fifteen").click(function(){
    $(".container").addClass("containerfifteen");
  });
  $(".sixteen").click(function(){
    $(".container").addClass("containersixteen");
  });

  

  